# Generated by Django 6.0.3 on 2026-04-03 01:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Шаблон альбома',
                'verbose_name_plural': 'Шаблоны альбомов',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название/буква класса')),
                ('graduation_year', models.IntegerField(verbose_name='Год выпуска')),
                ('parent_password', models.CharField(default=core.models.generate_random_password, max_length=50, verbose_name='Пароль для родителей')),
                ('teacher_name', models.CharField(blank=True, default='Классный руководитель', max_length=150, verbose_name='ФИО классного руководителя')),
                ('teacher_photo', models.ImageField(blank=True, null=True, upload_to='schools/teachers/', verbose_name='Фото классного руководителя')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фотография')),
                ('photo_type', models.CharField(choices=[('portrait', 'Портрет'), ('group', 'Групповое')], max_length=20, verbose_name='Тип фото')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='AlbumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generating', 'Генерация...'), ('ready', 'Готов'), ('error', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('zone_assignments', models.JSONField(blank=True, default=dict, help_text='Формат: {"<zone_id>": <photo_id>, ...}', verbose_name='Привязки фото к зонам')),
                ('pdf_file', models.FileField(blank=True, upload_to='albums/', verbose_name='PDF-файл')),
                ('zip_file', models.FileField(blank=True, upload_to='albums/', verbose_name='ZIP-архив')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.albumtemplate', verbose_name='Шаблон')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_orders', to='core.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Заказ альбома',
                'verbose_name_plural': 'Заказы альбомов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to='core.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Съемка',
                'verbose_name_plural': 'Съемки',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='PhotoSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('selected_photos', models.ManyToManyField(related_name='selections', to='core.photo', verbose_name='Выбранные фото')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_selection', to='core.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Выбор фото',
                'verbose_name_plural': 'Выборы фото',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.student', verbose_name='Ученик'),
        ),
        migrations.CreateModel(
            name='TemplateSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_order', models.PositiveIntegerField(default=1, help_text='1 = обложка, 2 = виньетка, 3-5 = групповые', verbose_name='Порядок')),
                ('spread_type', models.CharField(choices=[('cover', 'Обложка'), ('vignette', 'Виньетка (класс)'), ('group', 'Групповые фото')], max_length=20, verbose_name='Тип разворота')),
                ('background', models.ImageField(upload_to='templates/backgrounds/', verbose_name='Фоновое изображение')),
                ('bg_width', models.PositiveIntegerField(default=0, help_text='Заполняется автоматически', verbose_name='Ширина фона (px)')),
                ('bg_height', models.PositiveIntegerField(default=0, help_text='Заполняется автоматически', verbose_name='Высота фона (px)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='core.albumtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Разворот шаблона',
                'verbose_name_plural': 'Развороты шаблонов',
                'ordering': ['template', 'spread_order'],
                'unique_together': {('template', 'spread_order')},
            },
        ),
        migrations.CreateModel(
            name='TemplateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('hero', 'Портрет героя (обложка)'), ('teacher', 'Учитель'), ('student', 'Ученик (виньетка)'), ('group', 'Групповое фото')], max_length=20, verbose_name='Тип зоны')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Для учеников: определяет какой по алфавиту ребёнок попадёт в эту зону', verbose_name='Порядок сортировки')),
                ('x', models.PositiveIntegerField(verbose_name='X (px)')),
                ('y', models.PositiveIntegerField(verbose_name='Y (px)')),
                ('w', models.PositiveIntegerField(verbose_name='Ширина (px)')),
                ('h', models.PositiveIntegerField(verbose_name='Высота (px)')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.templatespread', verbose_name='Разворот')),
            ],
            options={
                'verbose_name': 'Зона шаблона',
                'verbose_name_plural': 'Зоны шаблонов',
                'ordering': ['spread', 'sort_order'],
            },
        ),
    ]
