# Generated by Django 6.0.3 on 2026-03-24 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('selected_photos', models.ManyToManyField(related_name='selections', to='core.photo', verbose_name='Выбранные фото')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_selection', to='core.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Выбор фото',
                'verbose_name_plural': 'Выборы фото',
            },
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to='core.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Съемка',
                'verbose_name_plural': 'Съемки',
            },
        ),
    ]
