# Generated by Django 6.0.3 on 2026-03-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photoselection_shoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.student', verbose_name='Ученик'),
        ),
    ]
