# Generated by Django 6.0.3 on 2026-03-24 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photo_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('page_count', models.PositiveIntegerField(default=5, verbose_name='Количество страниц')),
                ('cover_template', models.TextField(blank=True, help_text='Jinja2 HTML. Переменные: {{ class_name }}, {{ school_name }}, {{ year }}, {{ cover_image_url }}', verbose_name='HTML-шаблон обложки')),
                ('portrait_template', models.TextField(blank=True, help_text='Jinja2 HTML. Переменные: {{ students }} (список с .photo_url, .full_name), {{ page_num }}, {{ total_pages }}', verbose_name='HTML-шаблон портретов')),
                ('group_template', models.TextField(blank=True, help_text='Jinja2 HTML. Переменные: {{ group_photo_url }}, {{ class_name }}', verbose_name='HTML-шаблон групповых фото')),
            ],
            options={
                'verbose_name': 'Шаблон альбома',
                'verbose_name_plural': 'Шаблоны альбомов',
            },
        ),
        migrations.CreateModel(
            name='AlbumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, upload_to='album_covers/', verbose_name='Обложка')),
                ('pdf_file', models.FileField(blank=True, upload_to='albums/', verbose_name='PDF-файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group_photo_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_group1', to='core.photo', verbose_name='Групповое фото 1')),
                ('group_photo_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_group2', to='core.photo', verbose_name='Групповое фото 2')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_orders', to='core.schoolclass', verbose_name='Класс')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.albumtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Заказ альбома',
                'verbose_name_plural': 'Заказы альбомов',
                'ordering': ['-created_at'],
            },
        ),
    ]
