# Generated by Django 6.0.3 on 2026-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_albumtemplate_albumorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtemplate',
            name='hero_template',
            field=models.TextField(blank=True, help_text='Jinja2 HTML. Переменные: {{ hero.full_name }}, {{ hero.photo_url }}, {{ class_name }}', null=True, verbose_name='HTML-шаблон личной страницы ученика'),
        ),
    ]
