# Generated by Django 6.0.3 on 2026-03-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_albumtemplate_hero_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumtemplate',
            name='cover_template',
        ),
        migrations.RemoveField(
            model_name='albumtemplate',
            name='group_template',
        ),
        migrations.RemoveField(
            model_name='albumtemplate',
            name='hero_template',
        ),
        migrations.RemoveField(
            model_name='albumtemplate',
            name='portrait_template',
        ),
        migrations.AddField(
            model_name='albumtemplate',
            name='grid_spread_template',
            field=models.TextField(blank=True, help_text='Jinja2 HTML. @page { size: 430mm 350mm landscape; }. Переменные: {{ students }}, {{ class_name }}, {{ empty_cells }}, {{ range }}', verbose_name='HTML-разворот СЕТКИ КЛАССА (430×350mm)'),
        ),
        migrations.AddField(
            model_name='albumtemplate',
            name='hero_spread_template',
            field=models.TextField(blank=True, help_text='Jinja2 HTML. @page { size: 430mm 350mm landscape; }. Переменные: {{ hero.full_name }}, {{ hero.photo_url }}, {{ class_name }}', verbose_name='HTML-разворот VIP-ученика (430×350mm)'),
        ),
        migrations.AddField(
            model_name='albumtemplate',
            name='oblozhka_spread_template',
            field=models.TextField(blank=True, help_text='Jinja2 HTML. @page { size: 478mm 330mm landscape; }. Переменные: {{ class_name }}, {{ school_name }}, {{ year }}, {{ cover_image_url }}', verbose_name='HTML-разворот ОБЛОЖКИ (478×330mm)'),
        ),
    ]
