# Generated by Django 6.0.3 on 2026-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_albumtemplate_cover_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtemplate',
            name='grid_spread_bg',
            field=models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/', verbose_name='Фон: Разворот сетки класса'),
        ),
        migrations.AddField(
            model_name='albumtemplate',
            name='hero_spread_bg',
            field=models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/', verbose_name='Фон: Разворот VIP-ученика'),
        ),
        migrations.AddField(
            model_name='albumtemplate',
            name='oblozhka_bg',
            field=models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/', verbose_name='Фон: Разворот обложки'),
        ),
    ]
